version: "3"
services:
  front:
    container_name: front-end container
    image: 422divya/frontend:IMAGE_TAG
    environment:
      - API_URL: http://api:3001/data
    depends_on:
      - api
    networks:
      - network-frontend
    ports:
      - 3000:3000

  backend:
    container_name: api
    image: 422divya/backend:IMAGE_TAG
    networks:
      - network-db
      - network-frontend
    environment:
      - CONNECTION_STRING: postgres://demo_user:demo_user@db/demo_db
    depends_on: 
     - postgresldb

  postgresldb:
    container_name: db
    image: postgres:11.2-alpine
    environment:
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_user
      POSTGRES_DB: demo_db
    volumes:
        - ./init_sql_scripts/:/docker-entrypoint-initdb.d
    networks:
      - network-db


networks:
  network-db:
  network-frontend:
